### ISSUE TITLE
Notebook CRD exceeds size limits

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/odh-manifests#601] opened 2022-07-27 17:58 UTC
**Describe the bug**
Notebook CRD too big, we might be hitting an issue where the CRD exceeds size limit . `kubectl` apply doesn't work and operator is stuck for subsequent reconciliation

**Steps To Reproduce**
1. Install Open Data Hub operator 
2. Deploy https://github.com/opendatahub-io/odh-manifests/blob/master/kfdef/kfctl_odh_notebook_controller.yaml
3. Deploy any other KfDef

**Expected behavior**
All KfDefs are deployed

**Workaround (if any)**
Restart operator pod

**Comment by samuelvl** [comment] 2022-07-28 08:37
I can't reproduce the issue with kubectl, I think this is a problem related with kfctl:

``` 
kustomize build odh-notebook-controller/base | kubectl apply -f -
```

**Comment by VaishnaviHire** [comment] 2022-07-28 13:15
> I can't reproduce the issue with kubectl, I think this is a problem related with kfctl:
> 
> ```
> kustomize build odh-notebook-controller/base | kubectl apply -f -
> ```

So we are seeing this in kfctl, because it is a `client-side apply`. The issue doesn't occur in server-side apply

**Comment by samuelvl** [comment] 2022-07-28 13:31
@VaishnaviHire I see, can we fix this in kfctl code?

**Comment by samuelvl** [comment] 2022-08-02 08:21
Fixed in https://github.com/opendatahub-io/opendatahub-operator/pull/171

**Comment by andrewballantyne** [comment] 2022-08-03 00:41
@VaishnaviHire @samuelvl looks like the opendatahub-operator PR is approved but is on hold for unspecified reasons. Can we unhold it and get it merged to resolve this issue?

**Closed** 2022-08-04 20:48 UTC
Labels: kind/bug, priority/blocker
