### ISSUE TITLE
Notebook Images are failing to pull

### ISSUE THREAD

**Issue by anishasthana** [opendatahub-io/odh-manifests#829] opened 2023-05-24 13:50 UTC
We are seeing the following errors on most notebook images when we try to spin up a notebook server using the latest version (the 2023.1 tag) of notebook image. Using an older version of the image is working as expected.

```
failed to pull image "image-registry.openshift-image-registry.svc:5000/odh-applications/jupyter-minimal-notebook:2023.1": rpc error: code = Unknown desc = reading manifest 2023.1 in image-registry.openshift-image-registry.svc:5000/odh-applications/jupyter-minimal-notebook: unknown: unable to pull manifest from [quay.io/opendatahub/workbench-images@sha256:a2a96b9bd8d1aeae20a47197a9ed493a07c902fc0a3981d6109bb3659959c677](http://quay.io/opendatahub/workbench-images@sha256:a2a96b9bd8d1aeae20a47197a9ed493a07c902fc0a3981d6109bb3659959c677): manifest unknown: manifest unknown
```

cc @harshad16

**Comment by harshad16** [comment] 2023-05-24 14:35
The issue is due to the floating tag `weekly` which changes every week.

If the user installed the cluster a week before the old tag would not be available on the quay.
due to the floating tag and the image digest of the previous being orphaned and no longer available causing the issue of PullBack.

Temporary fix for this would be enable tag being up-to-date with external tag.
Permanent fix would be done via : https://github.com/opendatahub-io/notebooks/issues/103

**Comment by shalberd** [comment] 2023-05-26 20:28
Yes, they key thing is that the old digest is not present anymore for a weekly build tag such as ` jupyter-datascience-ubi9-python-3.9-2023a-weekly`

@harshad16 
Regarding "old tag would not be available on the quay":

The tag itself is always there, meaning the tag itself at quai io for -weekly does not change
` jupyter-datascience-ubi9-python-3.9-2023a-weekly`
 It is the image digest that changes. 

@VaishnaviHire  I made an error in thinking with respect to long-running notebooks when I assumed that the old digest would still be there in the internal openshift registry for such a tag, did I? ...

**Comment by harshad16** [comment] 2023-05-26 20:34
@shalberd Yes, I meant to write `old tag digest`. 
as you pointed the tag remains, the digested is not there anymore, that is what I meant with my comment.


About the internal registry, i think it would depend upon the cluster configuration as well right?

**Comment by shalberd** [comment] 2023-05-26 20:49
@harshad16 regarding "I made an error in thinking with respect to long-running notebooks when I assumed that the old digest / old image version would still be there in the internal openshift registry"

true, by all accounts I have seen, the old digest values were cached and still present in the openshift registry in the imagestream namespace. Could it be they were pruned in your case here?

Wait ... I think I understand .. of course, if you have a newly spun up cluster, even internally, that old digest is not available anymore in the internal registry. Or if pruning is set to aggressively. Plus, there are differences even for long-running clusters between on-prem and cloud, and image pruner cluster config, correct https://access.redhat.com/documentation/de-de/openshift_container_platform/4.10/html-single/registry/index#image-registry-on-cloud

**Comment by shalberd** [comment] 2023-05-26 21:08
The other thing that is an issue here:

`image-registry.openshift-image-registry.svc:5000/odh-applications/jupyter-minimal-notebook:2023.1`

if you were to use digest-format there, and internal image registry pruning would not be set too aggressively, then you could reference in the image-field by digest e.g. 

`image-registry.openshift-image-registry.svc:5000/odh-applications/jupyter-minimal-notebook@sha256:` and whatever the old hash value was, as it is in the cache of the internal openshift registry. 

The problem here is you refer to the tag, not digest.

For long-running-clusters, be aware though that any change of the image-digest, when doing scheduled: true on an imagestream tag, would lead to container restarts if using the image change trigger annotation.

Think about using the image change trigger annotation in future from odh dashboard, as that for one thing always gives you digest notation in the image-field of the StatefulSet / Pod container. And for another thing, it enabled you do have an additional switch paused: true to not react to image digest changes when scheduled: true or paused: false to react to image digest changes when scheduled: true.

https://docs.openshift.com/container-platform/4.10/openshift_images/triggering-updates-on-imagestream-changes.html#images-triggering-updates-imagestream-changes-kubernetes-about_triggering-updates-on-imagestream-changes 

This would also need to be coordinated with @andrewballantyne for the dashboard assembleNotebook / updateNotebook side of things. Right now, in `[PR 800](https://github.com/opendatahub-io/odh-dashboard/pull/800/files)` to be used together with [PR72](https://github.com/opendatahub-io/kubeflow/pull/72), paused were set to default: false, meaning that the image-field of the notebook container would react and update were there a change to the status / digest of the weekly image tag.

Sorry, so much at once, but this to me shows that my idea of letting openshift handle the lookup of image-field values via image trigger annotation is not just useful for disconnected environments.

**Comment by anishasthana** [comment] 2023-05-30 14:41
I'll defer to @harshad16 / @VaishnaviHire  on this as the notebook controller experts -- I just raised an issue as a user of the ODH notebooks. I'm happy to join as an additional source of feedback.

**Comment by harshad16** [comment] 2023-06-22 13:22
We have removed the weekly tag from main/master branch as well, and going forward will only use the sha digest format.
with this pattern, we wouldn't be falling into issue of tag not available.
Please view: https://github.com/opendatahub-io/odh-manifests/blob/master/notebook-images/base/params.env
closing the issue as complete.

**Closed by harshad16** 2023-06-22 13:22 UTC
Labels: kind/bug
